import { NextResponse } from "next/server"

export async function GET() {
  const tags = [
    // Characters - Popular across both sites
    { name: "hatsune_miku", series: "vocaloid", type: "character", count: 50000 },
    { name: "rem_(re:zero)", series: "re:zero", type: "character", count: 25000 },
    { name: "zero_two_(darling_in_the_franxx)", series: "darling_in_the_franxx", type: "character", count: 30000 },
    { name: "asuna_(sao)", series: "sword_art_online", type: "character", count: 20000 },
    { name: "2b_(nier:automata)", series: "nier:automata", type: "character", count: 35000 },
    { name: "nami_(one_piece)", series: "one_piece", type: "character", count: 15000 },
    { name: "ahri_(league_of_legends)", series: "league_of_legends", type: "character", count: 28000 },
    { name: "princess_zelda", series: "the_legend_of_zelda", type: "character", count: 22000 },
    { name: "bowsette", series: "super_mario_bros", type: "character", count: 18000 },
    { name: "tracer_(overwatch)", series: "overwatch", type: "character", count: 32000 },
    { name: "dva_(overwatch)", series: "overwatch", type: "character", count: 30000 },
    { name: "mercy_(overwatch)", series: "overwatch", type: "character", count: 28000 },
    { name: "widowmaker_(overwatch)", series: "overwatch", type: "character", count: 25000 },
    { name: "zelda", series: "the_legend_of_zelda", type: "character", count: 40000 },
    { name: "link", series: "the_legend_of_zelda", type: "character", count: 35000 },
    { name: "samus_aran", series: "metroid", type: "character", count: 20000 },
    { name: "peach", series: "super_mario_bros", type: "character", count: 18000 },
    { name: "rosalina", series: "super_mario_bros", type: "character", count: 15000 },
    { name: "pyra_(xenoblade)", series: "xenoblade_chronicles", type: "character", count: 22000 },
    { name: "mythra_(xenoblade)", series: "xenoblade_chronicles", type: "character", count: 20000 },

    // Artists - Popular creators on both platforms
    { name: "sakimichan", type: "artist", count: 15000 },
    { name: "cutesexyrobutts", type: "artist", count: 12000 },
    { name: "lewdreaper", type: "artist", count: 10000 },
    { name: "jlullaby", type: "artist", count: 8000 },
    { name: "dross", type: "artist", count: 7000 },
    { name: "incase", type: "artist", count: 9000 },
    { name: "sparrow", type: "artist", count: 11000 },
    { name: "aaaninja", type: "artist", count: 6000 },
    { name: "sssonic2", type: "artist", count: 5000 },
    { name: "derpixon", type: "artist", count: 13000 },
    { name: "flowerxl", type: "artist", count: 8500 },
    { name: "eltonel", type: "artist", count: 7500 },
    { name: "personalami", type: "artist", count: 9500 },
    { name: "dandonfuga", type: "artist", count: 10500 },
    { name: "dmitrys", type: "artist", count: 8000 },
    { name: "menoziriath", type: "artist", count: 6500 },
    { name: "supersatanson", type: "artist", count: 7000 },
    { name: "aka6", type: "artist", count: 9000 },
    { name: "anaxus", type: "artist", count: 8500 },
    { name: "shadman", type: "artist", count: 20000 },

    // Categories - Common classification tags
    { name: "solo", type: "category", count: 1000000 },
    { name: "1girl", type: "category", count: 900000 },
    { name: "2girls", type: "category", count: 500000 },
    { name: "multiple_girls", type: "category", count: 400000 },
    { name: "1boy", type: "category", count: 300000 },
    { name: "2boys", type: "category", count: 100000 },
    { name: "multiple_boys", type: "category", count: 80000 },
    { name: "1boy_1girl", type: "category", count: 250000 },
    { name: "group", type: "category", count: 200000 },
    { name: "futanari", type: "category", count: 150000 },
    { name: "yuri", type: "category", count: 180000 },
    { name: "yaoi", type: "category", count: 70000 },
    { name: "hetero", type: "category", count: 350000 },

    // Body types and features
    { name: "large_breasts", type: "body", count: 800000 },
    { name: "huge_breasts", type: "body", count: 600000 },
    { name: "small_breasts", type: "body", count: 400000 },
    { name: "medium_breasts", type: "body", count: 500000 },
    { name: "gigantic_breasts", type: "body", count: 200000 },
    { name: "flat_chest", type: "body", count: 150000 },
    { name: "thick_thighs", type: "body", count: 300000 },
    { name: "wide_hips", type: "body", count: 350000 },
    { name: "curvy", type: "body", count: 250000 },
    { name: "slim", type: "body", count: 200000 },
    { name: "muscular", type: "body", count: 180000 },
    { name: "petite", type: "body", count: 220000 },
    { name: "plump", type: "body", count: 160000 },
    { name: "athletic", type: "body", count: 140000 },
    { name: "voluptuous", type: "body", count: 190000 },

    // Clothing
    { name: "nude", type: "clothing", count: 700000 },
    { name: "bikini", type: "clothing", count: 300000 },
    { name: "lingerie", type: "clothing", count: 250000 },
    { name: "underwear", type: "clothing", count: 280000 },
    { name: "stockings", type: "clothing", count: 350000 },
    { name: "thighhighs", type: "clothing", count: 400000 },
    { name: "dress", type: "clothing", count: 200000 },
    { name: "school_uniform", type: "clothing", count: 180000 },
    { name: "maid", type: "clothing", count: 150000 },
    { name: "latex", type: "clothing", count: 120000 },
    { name: "bodysuit", type: "clothing", count: 160000 },
    { name: "leotard", type: "clothing", count: 140000 },
    { name: "pantyhose", type: "clothing", count: 200000 },
    { name: "kimono", type: "clothing", count: 90000 },
    { name: "swimsuit", type: "clothing", count: 220000 },
    { name: "one-piece_swimsuit", type: "clothing", count: 100000 },
    { name: "micro_bikini", type: "clothing", count: 80000 },
    { name: "sports_bra", type: "clothing", count: 70000 },
    { name: "yoga_pants", type: "clothing", count: 65000 },

    // Positions and poses
    { name: "standing", type: "pose", count: 500000 },
    { name: "sitting", type: "pose", count: 450000 },
    { name: "lying", type: "pose", count: 400000 },
    { name: "kneeling", type: "pose", count: 300000 },
    { name: "all_fours", type: "pose", count: 250000 },
    { name: "on_back", type: "pose", count: 350000 },
    { name: "spread_legs", type: "pose", count: 400000 },
    { name: "from_behind", type: "pose", count: 320000 },
    { name: "missionary", type: "pose", count: 180000 },
    { name: "cowgirl_position", type: "pose", count: 150000 },
    { name: "doggy_style", type: "pose", count: 200000 },
    { name: "bent_over", type: "pose", count: 220000 },
    { name: "squatting", type: "pose", count: 160000 },
    { name: "legs_up", type: "pose", count: 190000 },

    // Hair colors and styles
    { name: "long_hair", type: "hair", count: 900000 },
    { name: "short_hair", type: "hair", count: 400000 },
    { name: "medium_hair", type: "hair", count: 300000 },
    { name: "very_long_hair", type: "hair", count: 250000 },
    { name: "blonde_hair", type: "hair", count: 350000 },
    { name: "brown_hair", type: "hair", count: 320000 },
    { name: "black_hair", type: "hair", count: 400000 },
    { name: "red_hair", type: "hair", count: 280000 },
    { name: "blue_hair", type: "hair", count: 300000 },
    { name: "pink_hair", type: "hair", count: 250000 },
    { name: "white_hair", type: "hair", count: 220000 },
    { name: "silver_hair", type: "hair", count: 180000 },
    { name: "purple_hair", type: "hair", count: 200000 },
    { name: "green_hair", type: "hair", count: 150000 },
    { name: "orange_hair", type: "hair", count: 120000 },
    { name: "ponytail", type: "hair", count: 250000 },
    { name: "twintails", type: "hair", count: 200000 },
    { name: "braid", type: "hair", count: 160000 },
    { name: "bun", type: "hair", count: 100000 },

    // Quality and technical tags
    { name: "highres", type: "quality", count: 800000 },
    { name: "absurdres", type: "quality", count: 300000 },
    { name: "masterpiece", type: "quality", count: 250000 },
    { name: "best_quality", type: "quality", count: 200000 },
    { name: "high_resolution", type: "quality", count: 350000 },
    { name: "detailed", type: "quality", count: 400000 },
    { name: "very_detailed", type: "quality", count: 180000 },
    { name: "extremely_detailed", type: "quality", count: 150000 },
    { name: "official_art", type: "quality", count: 120000 },
    { name: "artist_name", type: "meta", count: 500000 },
    { name: "watermark", type: "meta", count: 300000 },
    { name: "signature", type: "meta", count: 280000 },

    // Series/Franchises
    { name: "pokemon", series: "pokemon", type: "series", count: 250000 },
    { name: "league_of_legends", series: "league_of_legends", type: "series", count: 180000 },
    { name: "overwatch", series: "overwatch", type: "series", count: 200000 },
    { name: "genshin_impact", series: "genshin_impact", type: "series", count: 220000 },
    { name: "fate/grand_order", series: "fate_series", type: "series", count: 180000 },
    { name: "azur_lane", series: "azur_lane", type: "series", count: 150000 },
    { name: "touhou", series: "touhou", type: "series", count: 300000 },
    { name: "kantai_collection", series: "kantai_collection", type: "series", count: 180000 },
    { name: "my_hero_academia", series: "my_hero_academia", type: "series", count: 140000 },
    { name: "naruto", series: "naruto", type: "series", count: 160000 },
    { name: "one_piece", series: "one_piece", type: "series", count: 150000 },
    { name: "dragon_ball", series: "dragon_ball", type: "series", count: 120000 },
    { name: "final_fantasy", series: "final_fantasy", type: "series", count: 140000 },
    { name: "persona", series: "persona", type: "series", count: 100000 },
    { name: "fire_emblem", series: "fire_emblem", type: "series", count: 120000 },
  ]

  return NextResponse.json({ tags, count: tags.length })
}
